### ISSUE TITLE
unofficial precompiled binary for FreeBSD 12-Beta1

### ISSUE THREAD

**Issue by ashleysommer** [jsm222/lxqt-freebsd#2]
Hello,
I've just installed FreeBSD 12-Beta1, and I want to install LXQT.
Using the instructions to install the unofficial precompiled binary, I am getting an error that the file does not exist.
Is it possible for the maintainers to build an unofficial pre-compiled binary for FreeBSD 12-Beta1 amd64?

**Comment by jsm222** [comment]
Hi I'm looking into building the packages. Most packages are already imported, so if you can't wait, you just need to import        

- audio/pavucontrol-qt
- editors/featherpad
- x11-wm/lxqt
- x11-wm/lxqt-session
to your portstree or to apply the patch attached **( not tested !!!)** [lxqt-missing.txt](https://github.com/jsm222/lxqt-freebsd/files/2511707/lxqt-missing.txt)

**Comment by jsm222** [comment]
The build completed earlier today see http://lxqt-freebsd.schmitz.computer/
```
lxqt: {
        url: "pkg+http://build.schmitz.computer/packages/${ABI}",
        mirror_type: "srv",
        enabled: yes,
        #signature_type: "pubkey",
        #pubkey: "/usr/local/etc/ssl/poudriere.cert", 
        priority: 100
}
```
