### ISSUE TITLE
power management

### ISSUE THREAD

**Issue by fabrice14** [jsm222/lxqt-freebsd#3]
Hello,

it is not reallly an issue, but a request
I would like to know why the lxqt power-management is not added in lxqt meta port for FreeBsd?

Thanks

**Comment by jsm222** [comment]
Hi good question. It was not ported yet, I think because of forgotten historical reasons.
Can you perhaps test commit ab4d5c55cf5d49320aa5bff5bb6c768c5e9d8e8f ?
It is still not in the meta package for lxqt or in the portstree yet though.

**Comment by fabrice14** [comment]
Hello,

OK, I understand.
No, we could not find it in the FreeBSD ports. It’s strange because the power management is used by Linux distributions. I guess that’s new.

Ok I will test it but not today. Maybe this week end.

Have a nice evening

Fabrice

**Comment by jsm222** [comment]
lxqt-powermanagement is about to be a port, see https://people.freebsd.org/~jsm/lxqt017.diff

**Comment by jsm222** [comment]
committed.

**Comment by fabrice14** [comment]
Thanks

Fabrice
